const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await ctx.newPage();
  page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 300)));
  page.on('console', (m) => { if (m.type() === 'error') console.log('[console]', m.text().slice(0, 200)) });
  page.setDefaultTimeout(15000);
  await page.goto('http://localhost:3000/login', { waitUntil: 'networkidle' });
  await page.fill('input[type="password"]', 'budu123456');
  await page.locator('input:not([type="password"])').first().fill('budu');
  await page.click('button[type="submit"], button:has-text("登录")');
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(2500);
  await page.locator('button:has-text("门店经营")').first().click();
  await page.waitForTimeout(600);
  await page.locator('button:has-text("POS 点单")').first().click();
  await page.waitForTimeout(3000);
  const ballCard = page.locator('[data-product-id]', { hasText: 'Balls-礼盒' }).first();
  console.log('Balls 卡片可见:', await ballCard.isVisible().catch(() => false));
  await ballCard.click({ force: true }).catch((e) => console.log('click err:', e.message));
  await page.waitForTimeout(1200);
  const dialogCount = await page.locator('[role="dialog"]').count();
  console.log('dialog 数:', dialogCount);
  const bodyHas = await page.locator('text=自由搭配').count();
  console.log('「自由搭配」出现:', bodyHas);
  await page.screenshot({ path: '/tmp/combo-dbg2.png' });
  await browser.close();
})().catch((e) => { console.error('异常:', e.message); process.exit(1); });
