import { webkit } from '@playwright/test'
const browser = await webkit.launch()
const page = await browser.newPage({ viewport: { width: 1024, height: 800 } })
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)))
await page.goto('http://127.0.0.1:5198/')
await page.waitForSelector('input', { timeout: 15000 })
await page.fill('input:not([type="password"])', 'budu')
await page.fill('input[type="password"]', 'BuduTest2026')
await page.getByRole('button', { name: /登 ?录/ }).first().click()
await page.waitForTimeout(4000)
await page.evaluate(() => { const el = [...document.querySelectorAll('button')].find((b) => b.textContent.includes('门店经营')); el && el.click() })
await page.waitForTimeout(1500)
await page.evaluate(() => {
  const els = [...document.querySelectorAll('button, span, div')].filter((b) => b.textContent.trim().includes('门店业绩录入'))
  const vis = els.filter((b) => { const r = b.getBoundingClientRect(); return r.width > 0 && r.height > 0 })
  vis[vis.length - 1].click()
})
await page.waitForTimeout(3000)
// 尝试删除今天这行业绩（PG 已停机）
page.once('dialog', async (d) => { console.log('DIALOG:', d.message().slice(0, 30)); await d.accept() })
await page.evaluate(() => {
  const btns = [...document.querySelectorAll('button')].filter((b) => b.getBoundingClientRect().width > 0 && b.getBoundingClientRect().top > 300)
  const del = btns.find((b) => b.querySelector('svg') && (b.getAttribute('aria-label') || '').includes('删除'))
  if (del) { del.click(); return 'delete btn clicked' }
  return 'no delete btn: ' + btns.map((b) => b.textContent.trim().slice(0, 10)).join('|').slice(0, 120)
}).then((r) => console.log(r))
await page.waitForTimeout(3500)
const body = await page.locator('body').innerText()
console.log('错误提示出现:', /保存失败|删除失败|PostgreSQL|失败/.test(body))
console.log('错误文本:', (body.match(/[^。\n]*(失败|不可用)[^。\n]*/g) || []).slice(0, 3))
await browser.close()
