import { webkit } from '@playwright/test'
const browser = await webkit.launch()
const page = await browser.newPage({ viewport: { width: 1024, height: 800 } })
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)))
await page.goto('http://127.0.0.1:5198/')
await page.waitForSelector('input', { timeout: 15000 })
await page.fill('input:not([type="password"])', 'budu')
await page.fill('input[type="password"]', 'BuduTest2026')
await page.getByRole('button', { name: /登 ?录/ }).first().click()
await page.waitForTimeout(4000)
// 门店经营 → 门店排班
await page.evaluate(() => { const el = [...document.querySelectorAll('button')].find((b) => b.textContent.includes('门店经营')); el && el.click() })
await page.waitForTimeout(1500)
await page.evaluate(() => {
  const els = [...document.querySelectorAll('button, span, div')].filter((b) => b.textContent.trim().includes('门店排班'))
  const vis = els.filter((b) => { const r = b.getBoundingClientRect(); return r.width > 0 && r.height > 0 })
  vis[vis.length - 1].click()
})
await page.waitForTimeout(3000)
const body = await page.locator('body').innerText()
console.log('排班页加载:', body.includes('门店排班'))
console.log('PG 数据可见（叶芷辰）:', body.includes('叶芷辰'))
console.log('班次可见（早班）:', body.includes('早班'))
// 添加一个班次：点第一个 添加排班
await page.evaluate(() => { const btn = [...document.querySelectorAll('button')].find((b) => b.textContent.includes('添加排班')); btn && btn.click() })
await page.waitForTimeout(1000)
const body2 = await page.locator('body').innerText()
console.log('弹窗打开:', body2.includes('添加员工排班'))
await browser.close()
