import { expect, test } from '@playwright/test'

test('Gate 27 A/B: 同店同名两行独立发放（金额/收件人/快照各归 Employee.id）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html')
  await expect(page.getByText('发放工资条', { exact: true })).toBeVisible()
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rows = page.locator('tbody tr')
  await expect(rows).toHaveCount(2)
  const texts = await rows.allInnerTexts()
  const a = texts.find((t) => t.includes('A001'))
  const b = texts.find((t) => t.includes('B001'))
  expect(a).toBeTruthy()
  expect(b).toBeTruthy()
  expect(a).toContain('@user-a')
  expect(b).toContain('@user-b')
  expect(a).toContain('¥1180.00') // 考勤 680 + 调整仅日 500
  expect(b).toContain('¥460.00') // 考勤按实际 6h 计 510 - 调整仅日 50
  // 全选发放
  await page.getByRole('button', { name: '全选' }).click()
  await page.getByRole('button', { name: /确认发放 2 份/ }).click()
  await expect(page.getByText(/已发放 2 份/)).toBeVisible()
  const posted = await page.evaluate(() => window.__posted)
  expect(posted.periodType).toBe('month')
  expect(posted.periodKey).toBe('2026-08')
  expect(posted.rows.length).toBe(2)
  const pa = posted.rows.find((r) => r.employeeId === 'emp-A')
  const pb = posted.rows.find((r) => r.employeeId === 'emp-B')
  expect(pa.employeeName).toBe('张伟')
  expect(pb.employeeName).toBe('张伟')
  expect(pa.totalCents).toBe(118000)
  expect(pb.totalCents).toBe(46000)
  expect(pa.snapshot.summary.total).toBe(1180)
  expect(pb.snapshot.summary.total).toBe(460)
  expect(pa.snapshot.summary.adjustment).toBe(500) // 仅调整日 +500（考勤日无调整）
  expect(pb.snapshot.summary.adjustment).toBe(-50)
  // 快照逐日明细：31 天；统一读取权威 payableHours；仅调整日真实表示（计薪工时 0）
  expect(pa.snapshot.days.length).toBe(31)
  const dayA01 = pa.snapshot.days.find((d) => d.day === '08-01')
  const dayB01 = pb.snapshot.days.find((d) => d.day === '08-01')
  const dayA10 = pa.snapshot.days.find((d) => d.day === '08-10')
  const dayB10 = pb.snapshot.days.find((d) => d.day === '08-10')
  expect(dayA01.payableHours).toBe(8)
  expect(dayA01.hasData).toBe(true)
  expect(dayB01.payableHours).toBe(6)
  expect(dayA10.payableHours).toBe(0)
  expect(dayA10.adjustment).toBe(500)
  expect(dayA10.pay).toBe(500)
  expect(dayB10.adjustment).toBe(-50)
  expect(dayB10.pay).toBe(-50)
})

test('Gate 27 C: LEGACY 月份硬阻断（0 发放）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?legacy=1')
  await expect(page.getByText('发放工资条', { exact: true })).toBeVisible()
  await expect(page.getByText(/该月份存在历史兼容工资数据，无法确认员工身份，暂不能发放工资条/)).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /确认发放/ })).toBeDisabled()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 D: 月度未全就绪，仅选就绪员工可发', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?unbound=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rows = page.locator('tbody tr')
  await expect(rows).toHaveCount(2)
  // 只选 emp-A（user-a 绑定）
  await rows.filter({ hasText: 'A001' }).click()
  await page.getByRole('button', { name: /确认发放 1 份/ }).click()
  await expect(page.getByText(/已发放 1 份/)).toBeVisible()
  const posted = await page.evaluate(() => window.__posted)
  expect(posted.rows.length).toBe(1)
  expect(posted.rows[0].employeeId).toBe('emp-A')
})

test('Gate 27 E: 选中就绪 + 未绑定 → 预检阻断，0 POST', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?unbound=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rows = page.locator('tbody tr')
  await expect(rows).toHaveCount(2)
  await rows.filter({ hasText: 'A001' }).click()
  await rows.filter({ hasText: 'B001' }).click()
  await page.getByRole('button', { name: /确认发放 2 份/ }).click()
  await expect(page.getByText(/以下员工暂不能发放/)).toBeVisible()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 F: 仅选未绑定员工 → 阻断', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?unbound=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rows = page.locator('tbody tr')
  await expect(rows).toHaveCount(2)
  await rows.filter({ hasText: 'B001' }).click()
  await page.getByRole('button', { name: /确认发放 1 份/ }).click()
  await expect(page.getByText(/以下员工暂不能发放/)).toBeVisible()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 H: 调整仅日员工（0 天 / 0 时 / 500）可见可发', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?adjonly=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const row = page.locator('tbody tr').filter({ hasText: 'A001' })
  await expect(row).toHaveCount(1)
  const text = await row.innerText()
  expect(text).toContain('0 天')
  expect(text).toContain('0h')
  expect(text).toContain('¥500.00')
  expect(text).toContain('@user-a')
  await row.click()
  await page.getByRole('button', { name: /确认发放 1 份/ }).click()
  await expect(page.getByText(/已发放 1 份/)).toBeVisible()
  const posted = await page.evaluate(() => window.__posted)
  expect(posted.rows.length).toBe(1)
  expect(posted.rows[0].employeeId).toBe('emp-A')
  expect(posted.rows[0].totalCents).toBe(50000)
  expect(posted.rows[0].snapshot.summary.workedDays).toBe(0)
  expect(posted.rows[0].snapshot.summary.payableHours).toBe(0)
  expect(posted.rows[0].snapshot.summary.total).toBe(500)
  // 快照逐日：仅调整日真实表示（计薪工时 0、调整 500），其余日 hasData=false
  const day10 = posted.rows[0].snapshot.days.find((d) => d.day === '08-10')
  expect(day10.hasData).toBe(true)
  expect(day10.payableHours).toBe(0)
  expect(day10.adjustment).toBe(500)
  expect(day10.pay).toBe(500)
  expect(posted.rows[0].snapshot.days.find((d) => d.day === '08-02').hasData).toBe(false)
})

test('Gate 27 I: 月份切换 → 状态对应所选月（7 月空月阻断）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  await page.locator('input[type="month"]').fill('2026-07')
  await expect(page.getByText(/该月份暂无可发放的稳定工资数据/)).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(0)
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 J: 竞态——迟到的 8 月响应不得覆盖已选的 7 月状态', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?race=1')
  // 立即切到 7 月（8 月考勤加载被 mock 延迟 400ms）
  await page.locator('input[type="month"]').fill('2026-07')
  await expect(page.getByText(/该月份暂无可发放的稳定工资数据/)).toBeVisible()
  // 等待迟到的 8 月响应返回后再断言：仍为 7 月状态
  await page.waitForTimeout(700)
  await expect(page.getByText(/该月份暂无可发放的稳定工资数据/)).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(0)
})

test('Gate 27 P: 周度/自定义周期保持可见但受控不可用（0 发放）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  // 周期 tabs 可见
  await expect(page.getByRole('button', { name: '周度' })).toBeVisible()
  await expect(page.getByRole('button', { name: '自定日期' })).toBeVisible()
  // 切到周度：受控不可用文案 + 无员工行 + 发放禁用 + 0 POST
  await page.getByRole('button', { name: '周度' }).click()
  await expect(page.getByText(/周度\/自定义周期尚未迁移至稳定工资计算，暂不可发放/)).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /确认发放/ })).toBeDisabled()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
  // 自定日期同理
  await page.getByRole('button', { name: '自定日期' }).click()
  await expect(page.getByText(/周度\/自定义周期尚未迁移至稳定工资计算，暂不可发放/)).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(0)
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 N1: 负工资员工单独选中 → 阻断（0 POST）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?negative=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rowB = page.locator('tbody tr').filter({ hasText: 'B001' })
  await expect(rowB).toContainText('¥-290.00') // 考勤按实际 6h 计 510 - 调整仅日 800
  await rowB.click()
  await page.getByRole('button', { name: /确认发放 1 份/ }).click()
  await expect(page.getByText(/工资金额为负/)).toBeVisible()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 N2: 就绪 + 负工资一起选中 → 整批阻断（0 POST）', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?negative=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rows = page.locator('tbody tr')
  await rows.filter({ hasText: 'A001' }).click()
  await rows.filter({ hasText: 'B001' }).click()
  await page.getByRole('button', { name: /确认发放 2 份/ }).click()
  await expect(page.getByText(/工资金额为负/)).toBeVisible()
  expect(await page.evaluate(() => window.__posted)).toBeNull()
})

test('Gate 27 N3: 负工资未选中 → 不阻断就绪员工发放', async ({ page }) => {
  await page.goto('/tests/gate27-issue-harness.html?negative=1')
  await expect(page.getByText('稳定计算', { exact: true })).toBeVisible()
  const rowA = page.locator('tbody tr').filter({ hasText: 'A001' })
  await rowA.click()
  await page.getByRole('button', { name: /确认发放 1 份/ }).click()
  await expect(page.getByText(/已发放 1 份/)).toBeVisible()
  const posted = await page.evaluate(() => window.__posted)
  expect(posted.rows.length).toBe(1)
  expect(posted.rows[0].employeeId).toBe('emp-A')
})
