import { expect, test } from '@playwright/test'
import * as XLSX from 'xlsx'

test('订单记录页展示列表、筛选、明细与导出', async ({ page }) => {
  await page.goto('/tests/order-records-harness.html')
  await expect(page.getByText('共 3 笔订单', { exact: true })).toBeVisible()
  await expect(page.getByText('POS-TEST-ORDER-001', { exact: true })).toBeVisible()
  await expect(page.getByText('POS-TEST-ORDER-002', { exact: true })).toBeVisible()

  await page.getByLabel('支付方式').selectOption('cash')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(page.getByText('共 2 笔订单', { exact: true })).toBeVisible()
  await expect(page.getByText('POS-TEST-ORDER-001', { exact: true })).toBeVisible()
  await expect(page.getByText('POS-TEST-ORDER-002', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: /明细/ }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('卡皮巴拉布丁', { exact: true })).toBeVisible()
  await expect(dialog.getByText('PAY-TEST-1', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '完成', exact: true }).click()
  await expect(dialog).toHaveCount(0)

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出 Excel', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/budu订单记录_.+\.xlsx/)
  const stream = await download.createReadStream()
  const chunks = []
  for await (const chunk of stream) chunks.push(chunk)
  const wb = XLSX.read(Buffer.concat(chunks), { type: 'buffer' })
  expect(wb.SheetNames).toEqual(['订单列表', '商品明细'])
  const orderSheet = XLSX.utils.sheet_to_json(wb.Sheets['订单列表'], { header: 1 })
  expect(orderSheet[0]).toContain('商品明细')
  expect(orderSheet.some((row) => row.includes('卡皮巴拉布丁×1'))).toBe(true)
  const itemSheet = XLSX.utils.sheet_to_json(wb.Sheets['商品明细'], { header: 1 })
  expect(itemSheet[0]).toEqual(['订单号', '商品名称', 'SKU', '单价（元）', '数量', '小计（元）'])
  expect(itemSheet.some((row) => row.includes('卡皮巴拉布丁'))).toBe(true)
})

test('开发者可删除订单，删除后列表刷新', async ({ page }) => {
  page.on('dialog', (dialog) => dialog.accept())
  await page.goto('/tests/order-records-harness.html')
  await expect(page.getByText('共 3 笔订单', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /删除/ }).first().click()
  await expect(page.getByText('共 2 笔订单', { exact: true })).toBeVisible()
  await expect(page.getByText('POS-TEST-ORDER-001', { exact: true })).toHaveCount(0)
  await expect(page.getByText('POS-TEST-ORDER-002', { exact: true })).toBeVisible()
})

test('整单退款后订单变为已退款', async ({ page }) => {
  await page.goto('/tests/order-records-harness.html')
  await page.getByRole('button', { name: /退款 POS-TEST-ORDER-001/ }).click()
  const dialog = page.getByRole('dialog', { name: '订单退款' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('整单退款', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '确认退款', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'POS-TEST-ORDER-001' }).getByText('已退款', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /退款 POS-TEST-ORDER-001/ })).toHaveCount(0)
  await page.getByRole('button', { name: /明细/ }).first().click()
  await expect(page.getByRole('dialog', { name: '订单明细' }).getByText('退款记录', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: '订单明细' }).getByText(/卡皮巴拉布丁×1/)).toBeVisible()
})

test('部分退款按商品退指定数量', async ({ page }) => {
  await page.goto('/tests/order-records-harness.html')
  await page.getByRole('button', { name: /退款 POS-TEST-ORDER-003/ }).click()
  const dialog = page.getByRole('dialog', { name: '订单退款' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '部分退款', exact: true }).click()
  const puddingRow = dialog.locator('tr').filter({ hasText: '卡皮巴拉布丁' })
  await puddingRow.locator('input').fill('1')
  await expect(dialog.locator('tfoot').getByText('¥72.00', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '确认退款', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'POS-TEST-ORDER-003' }).getByText('部分退款', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /明细/ }).last().click()
  const detail = page.getByRole('dialog', { name: '订单明细' })
  await expect(detail.getByText('退款记录', { exact: true })).toBeVisible()
  await expect(detail.getByText(/卡皮巴拉布丁×1/)).toBeVisible()
})
