import { expect, test } from '@playwright/test'

async function openShipment(page) {
  await page.goto('/tests/partner-replenishment-shipment-harness.html')
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  await expect(page.getByRole('dialog', { name: /审核补货单/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: '物流履约' })).toBeVisible()
}

test('默认官舍，可选择其他门店，并仅提交物流与本批数量', async ({ page }) => {
  await openShipment(page)
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('发货门店')).toHaveValue('guanshe')
  await dialog.getByLabel('发货门店').selectOption('tongying')
  await dialog.getByLabel('运费方式').selectOption('COLLECT')
  await dialog.getByLabel('快递公司').fill('顺丰')
  await dialog.getByLabel('快递单号').fill('SF123456789')
  await dialog.getByLabel('KG 糖本次发货数量').fill('6000')
  await dialog.getByRole('button', { name: '确认发货' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.requests[0])).toMatchObject({ body: { fulfillmentStoreKey: 'tongying', carrier: '顺丰', trackingNumber: 'SF123456789', freightType: 'COLLECT', items: [{ orderItemId: 'kg-line', shippedQuantityBase: 6000 }] } })
  const request = await page.evaluate(() => window.__partnerShipmentTest.requests[0])
  expect(request.idempotencyKey).toMatch(/^shipment-[0-9a-f-]{36}$/)
  expect(JSON.stringify(request.body)).not.toMatch(/partnerId|price|discount|stock|payment/i)
})

test('removed line 不可进入发货，UI 展示已发和待发', async ({ page }) => {
  await openShipment(page)
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('颗糖本次发货数量')).toHaveCount(0)
  await expect(dialog.getByText('已发 0 kg · 待发 10 kg')).toBeVisible()
})

for (const width of [320, 340, 375, 390, 430, 768, 1024, 1440]) {
  test(`${width}px 发货 Sheet 无横向溢出且确认按钮可达`, async ({ page }) => {
    await page.setViewportSize({ width, height: 820 })
    await openShipment(page)
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByRole('button', { name: '确认发货' })).toBeVisible()
    const box = await dialog.boundingBox()
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(width + 1)
  })
}

async function openPartial(page) {
  await page.goto('/tests/partner-replenishment-shipment-harness.html?partial=1&multi=1')
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  return page.getByRole('dialog', { name: /审核补货单/ })
}
test('部分发货按全部商品真实剩余量预填，只改单项，取消重开取新剩余', async ({ page }) => {
  let dialog = await openPartial(page)
  await expect(dialog.getByLabel('KG 糖本次发货数量')).toHaveValue('6000')
  await expect(dialog.getByLabel('NO.2柠檬本次发货数量')).toHaveValue('80')
  await expect(dialog.getByLabel('散糖袋本次发货数量')).toHaveValue('2')
  expect(await page.evaluate(() => window.__partnerShipmentTest.requests.length)).toBe(0)
  await dialog.getByLabel('KG 糖本次发货数量').fill('2000')
  await dialog.getByLabel('快递公司').fill('顺丰')
  await dialog.getByLabel('快递单号').fill('LOCAL-MOCK-ONLY')
  await dialog.getByRole('button', { name: '确认发货' }).click()
  await expect(dialog).toHaveCount(0)
  expect(await page.evaluate(() => window.__partnerShipmentTest.requests[0].body.items)).toEqual([
    { orderItemId: 'kg-line', shippedQuantityBase: 2000 }, { orderItemId: 'pcs-approved', shippedQuantityBase: 80 }, { orderItemId: 'native-approved', shippedQuantityBase: 2 },
  ])
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  dialog = page.getByRole('dialog', { name: /审核补货单/ })
  await expect(dialog.getByLabel('KG 糖本次发货数量')).toHaveValue('4000')
  await expect(dialog.getByLabel('NO.2柠檬本次发货数量')).toHaveValue('0')
  await expect(dialog.getByLabel('NO.2柠檬本次发货数量')).toBeDisabled()
  await dialog.getByLabel('KG 糖本次发货数量').fill('1000')
  await dialog.getByRole('button', { name: '关闭审核' }).click()
  expect(await page.evaluate(() => window.__partnerShipmentTest.requests.length)).toBe(1)
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  await expect(page.getByLabel('KG 糖本次发货数量')).toHaveValue('4000')
})
test('刷新与同单异步详情不覆盖正在编辑的量，切单不会沿用另一单草稿', async ({ page }) => {
  const dialog = await openPartial(page)
  await dialog.getByLabel('KG 糖本次发货数量').fill('2000')
  await page.getByRole('button', { name: '刷新', exact: true }).evaluate(button => button.click())
  await expect(dialog.getByLabel('KG 糖本次发货数量')).toHaveValue('2000')
  await page.evaluate(() => { window.__partnerShipmentTest.order.items[0].remainingQuantityBase = 5000 })
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).evaluate(button => button.click())
  await expect(dialog.getByText('已发 4 kg · 待发 5 kg')).toBeVisible()
  await expect(dialog.getByLabel('KG 糖本次发货数量')).toHaveValue('2000')
  await dialog.getByRole('button', { name: '关闭审核' }).click()
  await page.getByRole('button', { name: /RPL-OTHER/ }).click()
  await expect(page.getByLabel('KG 糖本次发货数量')).toHaveValue('2000')
  await page.getByLabel('KG 糖本次发货数量').fill('500')
  await page.getByRole('button', { name: '关闭审核' }).click()
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  await expect(page.getByLabel('KG 糖本次发货数量')).toHaveValue('5000')
})
test('乱序切单响应和关闭后的迟到响应不会切回旧单或重新打开', async ({ page }) => {
  await page.goto('/tests/partner-replenishment-shipment-harness.html')
  await expect(page.getByRole('button', { name: /RPL-OTHER/ })).toBeVisible()
  await page.evaluate(() => { window.__partnerShipmentTest.holdDetails = true })
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).click()
  await page.getByRole('button', { name: /RPL-OTHER/ }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.detailPending.length)).toBe(2)
  await page.evaluate(() => window.__partnerShipmentTest.detailPending[1]())
  await expect(page.getByRole('dialog')).toContainText('RPL-OTHER')
  await page.evaluate(() => window.__partnerShipmentTest.detailPending[0]())
  await page.evaluate(() => new Promise(requestAnimationFrame))
  await expect(page.getByRole('dialog')).toContainText('RPL-OTHER')
  await page.getByRole('button', { name: /RPL-20260907-SHIPMENT/ }).evaluate(button => button.click())
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.detailPending.length)).toBe(3)
  await page.getByRole('button', { name: '关闭审核' }).click()
  await page.evaluate(() => window.__partnerShipmentTest.detailPending[2]())
  await page.evaluate(() => new Promise(requestAnimationFrame))
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('保留合作商数量规则、服务器并发拒绝和编辑值，重复点击只发一次请求', async ({ page }) => {
  const dialog = await openPartial(page)
  await dialog.getByLabel('快递公司').fill('顺丰')
  await dialog.getByLabel('快递单号').fill('LOCAL-MOCK-ONLY')
  for (const value of ['6001', '-1', '1.5']) {
    await dialog.getByLabel('KG 糖本次发货数量').fill(value)
    await dialog.getByRole('button', { name: '确认发货' }).click()
    await expect(dialog.getByRole('alert')).toContainText('非负整数')
  }
  expect(await page.evaluate(() => window.__partnerShipmentTest.requests.length)).toBe(0)
  await dialog.getByLabel('KG 糖本次发货数量').fill('2000')
  await page.evaluate(() => { window.__partnerShipmentTest.error = '发货数量超过剩余确认数量'; window.__partnerShipmentTest.holdShipments = true })
  await dialog.getByRole('button', { name: '确认发货' }).evaluate(button => { button.click(); button.click() })
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.requests.length)).toBe(1)
  await page.evaluate(() => window.__partnerShipmentTest.shipmentPending[0]())
  await expect(dialog.getByRole('alert')).toContainText('发货数量超过剩余确认数量')
  await expect(dialog.getByLabel('KG 糖本次发货数量')).toHaveValue('2000')
  expect(await page.evaluate(() => window.__partnerShipmentTest.order.items[0].remainingQuantityBase)).toBe(6000)
})

test('旧单发货的迟到成功不会关闭新单或丢失新单编辑', async ({ page }) => {
  const dialog = await openPartial(page)
  await dialog.getByLabel('快递公司').fill('顺丰')
  await dialog.getByLabel('快递单号').fill('LOCAL-MOCK-ONLY')
  await dialog.getByLabel('KG 糖本次发货数量').fill('2000')
  await page.evaluate(() => { window.__partnerShipmentTest.holdShipments = true })
  await dialog.getByRole('button', { name: '确认发货' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.shipmentPending.length)).toBe(1)
  await dialog.getByRole('button', { name: '关闭审核' }).click()
  await page.getByRole('button', { name: /RPL-OTHER/ }).click()
  await page.getByLabel('KG 糖本次发货数量').fill('500')
  await page.evaluate(() => window.__partnerShipmentTest.shipmentPending[0]())
  await expect.poll(() => page.evaluate(() => window.__partnerShipmentTest.order.items[0].remainingQuantityBase)).toBe(4000)
  await expect(page.getByRole('dialog')).toContainText('RPL-OTHER')
  await expect(page.getByLabel('KG 糖本次发货数量')).toHaveValue('500')
})
