import { expect, test } from '@playwright/test'

test('合作商供货首页使用任务卡、物流与货款双状态及对账筛选', async ({ page }) => {
  await page.goto('/tests/partner-supply-harness.html')
  await expect(page.getByRole('heading', { name: '合作商供货' })).toBeVisible()
  await expect(page.getByLabel('合作商筛选')).toBeVisible()
  await expect(page.getByLabel('发货门店筛选')).toBeVisible()
  await expect(page.getByLabel('货款筛选')).toBeVisible()
  await expect(page.getByRole('button', { name: '待备货' })).toBeVisible()
  await expect(page.getByRole('button', { name: '已发货' })).toBeVisible()
  await expect(page.locator('span').filter({ hasText: /^部分收款$/ }).first()).toBeVisible()
  await expect(page.locator('span').filter({ hasText: /^已结清$/ }).first()).toBeVisible()
  await expect(page.getByText('供货金额', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /导出对账 Excel/ })).toBeVisible()
})

test('创建供货单默认带出合作商政策并复用分类、搜索、多选与数量编辑', async ({ page }) => {
  await page.goto('/tests/partner-supply-harness.html')
  await page.getByRole('button', { name: /创建供货单/ }).click()
  const sheet = page.getByTestId('partner-supply-create')
  await expect(sheet.getByLabel('合作商')).toHaveValue('partner-qhd')
  await expect(sheet.getByLabel('发货门店')).toHaveValue('guanshe')
  await expect(sheet.getByLabel('合作折扣')).toHaveValue('65')
  await expect(sheet.getByText('合作政策：零售价 × 65%')).toBeVisible()
  await sheet.getByRole('button', { name: '糖果', exact: true }).click()
  await expect(sheet.getByText('NO.1树莓', { exact: true })).toBeVisible()
  await expect(sheet.getByText('NO.2柠檬', { exact: true })).toHaveCount(0)
  await sheet.getByLabel('搜索产品').fill('NO.1')
  await sheet.getByRole('button', { name: /NO\.1树莓/ }).click()
  await sheet.getByLabel('批量设置数量').fill('20')
  await sheet.getByRole('button', { name: '应用到已选' }).click()
  await expect(sheet.getByLabel('NO.1树莓数量')).toHaveValue('20')
  await sheet.getByLabel('NO.1树莓数量').fill('100')
  await expect(sheet.getByText('¥325.00', { exact: true })).toBeVisible()
  await sheet.getByRole('button', { name: '核对并提交' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerSupplyTest.requests.find((item) => item.type === 'order-create')?.body)).toMatchObject({ partnerId: 'partner-qhd', fromStoreKey: 'guanshe', effectiveDiscountBps: 6500, items: [{ productId: 'p1', quantity: 100 }] })
})

test('无正式零售价产品不可选择，未分类产品可按编号搜索', async ({ page }) => {
  await page.goto('/tests/partner-supply-harness.html')
  await page.getByRole('button', { name: /创建供货单/ }).click()
  const sheet = page.getByTestId('partner-supply-create')
  await sheet.getByRole('button', { name: '礼盒', exact: true }).click()
  await expect(sheet.getByRole('button', { name: /礼盒套装/ })).toBeDisabled()
  await expect(sheet.getByText('未设零售价')).toBeVisible()
  await sheet.getByRole('button', { name: '未分类', exact: true }).click()
  await sheet.getByLabel('搜索产品').fill('NO.2')
  await expect(sheet.getByRole('button', { name: /NO\.2柠檬/ })).toBeVisible()
})

test('合作商管理支持新增编辑门店折扣与停用且不提供物理删除', async ({ page }) => {
  await page.goto('/tests/partner-supply-harness.html')
  await page.getByRole('button', { name: /合作商管理/ }).click()
  const manager = page.getByTestId('partner-manager')
  await expect(manager).toContainText('历史供货单 2 张')
  await expect(manager.getByRole('button', { name: /删除/ })).toHaveCount(0)
  await manager.getByRole('button', { name: '新增' }).click()
  await manager.getByText('合作商名称').locator('input').fill('天津合作商')
  await manager.getByText('默认发货门店').locator('select').selectOption('guanshe')
  await manager.getByText('默认合作折扣').locator('input').fill('70')
  await manager.getByRole('button', { name: '保存' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerSupplyTest.requests.some((item) => item.type === 'partner-create' && item.body.name === '天津合作商'))).toBe(true)
})

test('详情保留冻结价格、逐笔收款、发货留痕并生成正式图片', async ({ page }) => {
  await page.goto('/tests/partner-supply-harness.html')
  await page.getByRole('button', { name: '查看详情' }).first().click()
  const detail = page.getByTestId('partner-supply-detail')
  await expect(detail).toContainText('零售价 ¥5.00 × 65%')
  await expect(detail).toContainText('已收¥200.00')
  await expect(detail).toContainText('待收¥125.00')
  await detail.getByRole('button', { name: '导出图片' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerSupplyTest.imageExports)).toBeGreaterThan(0)
  await detail.getByRole('button', { name: '登记收款' }).click()
  await page.getByLabel('本次收款').fill('125')
  await page.getByLabel('收款日期').fill('2026-08-29')
  await page.getByRole('button', { name: '确认登记' }).click()
  await expect.poll(() => page.evaluate(() => window.__partnerSupplyTest.requests.find((item) => item.type === 'receipt')?.body.amountCents)).toBe('12500')
  await expect(page.getByTestId('partner-supply-detail')).toContainText('已结清')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByTestId('partner-supply-detail').getByRole('button', { name: '确认发货' }).click()
  await expect(page.getByTestId('partner-supply-detail')).toContainText('已发货')
})

for (const width of [320, 340, 375, 390, 430]) {
  test(`${width}px 首页、创建与详情无横向穿模`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tests/partner-supply-harness.html')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    await page.getByRole('button', { name: /创建供货单/ }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    await page.getByRole('button', { name: '关闭弹窗' }).click()
    await page.getByRole('button', { name: '查看详情' }).first().click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
  })
}
