import { expect, test } from '@playwright/test'

test('既有物料分类同时展示4项商品与旧物料，旧入口进入商品中心',async({page})=>{
 await page.goto('/tests/product-material-harness.html')
 await expect(page.getByRole('heading',{name:'商品中心',exact:true})).toBeVisible()
 await expect(page.locator('[data-product-id]')).toHaveCount(5)
 await page.getByLabel('业务状态筛选').selectOption('all')
 await expect(page.locator('[data-product-id]')).toHaveCount(6)
 await expect(page.getByRole('button',{name:'删除',exact:true})).toHaveCount(0)
 await expect(page.getByText('冰袋',{exact:true})).toBeVisible()
})

test('物料新增/编辑保持原ID编号及4项商品全部字段',async({page})=>{
 await page.goto('/tests/product-material-harness.html')
 const original=await page.evaluate(()=>JSON.stringify(window.__productMaterialTest.products))
 await page.getByRole('button',{name:'新增物料',exact:true}).click()
 await page.getByLabel('物料名称',{exact:true}).fill('新物料')
 await expect(page.getByLabel('物料零售价（元）',{exact:true})).toHaveValue('0.10')
 await expect(page.getByLabel('物料成本价（元）',{exact:true})).toHaveValue('0.10')
 await expect(page.getByLabel('合作商可补货',{exact:true})).not.toBeChecked()
 await page.getByLabel('排序',{exact:true}).fill('8')
 await page.getByRole('button',{name:'保存物料',exact:true}).click()
 await expect(page.locator('[data-product-id="new-2"]')).toContainText('新物料')
 await page.getByRole('button',{name:'编辑新物料',exact:true}).click()
 await expect(page.getByLabel('SKU',{exact:true})).toHaveAttribute('readonly','')
 await page.getByLabel('物料名称',{exact:true}).fill('新物料箱')
 await page.getByLabel('排序',{exact:true}).fill('2')
 await page.getByLabel('门店调拨启用',{exact:true}).uncheck()
 await page.getByRole('button',{name:'保存物料',exact:true}).click()
 await page.getByLabel('业务状态筛选').selectOption('all')
 await expect(page.locator('[data-product-id="new-2"]')).toContainText('新物料箱')
 const result=await page.evaluate(()=>({products:JSON.stringify(window.__productMaterialTest.products),row:window.__productMaterialTest.rows.find(r=>r.id==='new-2'),requests:window.__productMaterialTest.requests.filter(r=>r.method!=='GET')}))
 expect(result.products).toBe(original)
 expect(result.row).toMatchObject({id:'new-2',sku:'BUDU-MAT-new-2',code:'BUDU-MAT-new-2',enabled:false,partnerReplenishmentEnabled:false,version:2})
 expect(result.requests.map(r=>r.path)).toEqual(['/api/v2/transfer-master-items','/api/v2/transfer-master-items/new-2'])
})

test('后续开启物料补货需显式单位和独立报价',async({page})=>{
 await page.goto('/tests/product-material-harness.html')
 await page.getByRole('button',{name:'编辑冰袋',exact:true}).click()
 await page.getByLabel('合作商可补货',{exact:true}).check()
 await page.getByLabel('物料补货方式',{exact:true}).selectOption('NATIVE')
 await expect(page.getByLabel(/独立补货标准报价/)).toHaveValue('')
 await page.getByLabel('物料单位',{exact:true}).fill('包')
 await page.getByLabel(/独立补货标准报价/).fill('2.00')
 await page.getByRole('button',{name:'保存物料',exact:true}).click()
 const request=await page.evaluate(()=>window.__productMaterialTest.requests.find(r=>r.method==='PUT'))
 expect(request.body).toMatchObject({partnerReplenishmentEnabled:true,partnerOrderUnit:'NATIVE',unit:'包',partnerMaterialPriceCents:'200',salePriceCents:'10'})
})

for(const scope of ['both','product','material','none'])test(`${scope}权限组合仅读取各自权威`,async({page})=>{
 await page.goto(`/tests/product-material-harness.html?scope=${scope}`)
 await expect(page.getByText('正在加载商品…')).toHaveCount(0)
 const reads=await page.evaluate(()=>window.__productMaterialTest.requests.map(r=>r.path))
 expect(reads.includes('/api/v2/products')).toBe(['both','product'].includes(scope))
 expect(reads.includes('/api/v2/transfer-master-items?category=material')).toBe(['both','material'].includes(scope))
 await expect(page.getByRole('button',{name:'新增商品',exact:true})).toHaveCount(['both','product'].includes(scope)?1:0)
 await expect(page.getByRole('button',{name:'新增物料',exact:true})).toHaveCount(['both','material'].includes(scope)?1:0)
})

for(const width of [320,340,375,390,430,1024,1440])test(`${width}px 物料编辑可滚动，保存按钮可见且无页面横向滚动`,async({page})=>{
 await page.setViewportSize({width,height:width===1024?768:900})
 await page.goto('/tests/product-material-harness.html')
 await page.getByRole('button',{name:'编辑冰袋',exact:true}).click()
 await page.getByLabel('合作商可补货',{exact:true}).check()
 await page.getByLabel('物料补货方式',{exact:true}).selectOption('NATIVE')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBe(0)
 await expect(page.getByRole('button',{name:'保存物料',exact:true})).toBeInViewport()
 await page.getByLabel(/独立补货标准报价/).scrollIntoViewIfNeeded()
 await expect(page.getByLabel(/独立补货标准报价/)).toBeInViewport()
 if([390,1024,1440].includes(width))await page.screenshot({path:`test-results/material-editor-${width}.png`,fullPage:false})
})


test('分类同名歧义时不取首项，不展示或编辑旧物料',async({page})=>{
 await page.goto('/tests/product-material-harness.html?ambiguous=1')
 await expect(page.getByText('物料分类存在同名歧义，已暂停物料展示和编辑，请核对分类 ID')).toBeVisible()
 await expect(page.getByRole('button',{name:'新增物料',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'全部',exact:true}).click()
 await expect(page.locator('[data-product-id="m-used"]')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'编辑冰袋',exact:true})).toHaveCount(0)
})
