import { expect, test } from '@playwright/test'

test('采购信息、添加货品与申请列表形成清晰层级', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/tests/purchase-harness.html')
  const information = page.getByTestId('purchase-information')
  await expect(information.getByRole('heading', { name: '采购信息' })).toBeVisible()
  await expect(information.getByLabel('采购门店')).toBeVisible()
  await expect(information.getByLabel('供应商')).toBeVisible()
  await expect(information.getByLabel('预计到货日期')).toBeVisible()
  await expect(page.getByTestId('purchase-item-builder').getByRole('heading', { name: '添加货品' })).toBeVisible()
  await expect(page.getByRole('button', { name: '提交采购申请' })).toBeDisabled()
  const pending = page.locator('[data-purchase-request-id="purchase-pending"]')
  await expect(pending).toContainText('北京测试供应商')
  await expect(pending).toContainText('北京通盈中心店')
  await expect(pending).toContainText('166颗')
  await expect(pending).toContainText('100件')
  await expect(pending.getByRole('button', { name: '收货入库' })).toBeVisible()
  await expect(pending.getByRole('button', { name: '安全删除' })).toHaveClass(/bg-transparent/)
})

test('已选商品使用真实单位并启用唯一主 CTA', async ({ page }) => {
  await page.goto('/tests/purchase-harness.html')
  await page.getByRole('button', { name: '选择产品' }).click()
  await page.getByTestId('purchase-product-menu').getByText('NO.2柠檬', { exact: true }).click()
  await page.getByRole('button', { name: '确定' }).click()
  await page.getByLabel('采购数量').fill('166')
  await page.getByLabel('货品备注').fill('周末补货')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  const builder = page.getByTestId('purchase-item-builder')
  await expect(builder).toContainText('NO.2柠檬')
  await expect(builder).toContainText('颗')
  await expect(builder).toContainText('周末补货')
  await expect(page.getByRole('button', { name: '提交采购申请' })).toBeEnabled()
})

test('收货错误只显示在对应采购单且处理中防重复', async ({ page }) => {
  await page.goto('/tests/purchase-harness.html')
  const pending = page.locator('[data-purchase-request-id="purchase-pending"]')
  page.once('dialog', (dialog) => dialog.accept())
  await pending.getByRole('button', { name: '收货入库' }).click()
  await expect(pending.getByRole('button', { name: '正在入库…' })).toBeDisabled()
  await expect(pending.getByRole('alert')).toHaveText('收货入库失败，库存未发生变化，请稍后重试。')
  await expect(page.getByTestId('purchase-item-builder')).not.toContainText('收货入库失败')
  expect(await page.evaluate(() => window.__purchaseTest.receiveAttempts)).toBe(1)
  await expect(page.getByText(/Invalid.*prisma|Unknown argument|StockLedger/i)).toHaveCount(0)
})

test('收货成功刷新状态并只触发一次成功反馈', async ({ page }) => {
  await page.goto('/tests/purchase-harness.html')
  await page.evaluate(() => { window.__purchaseTest.receiveFailure = false })
  const pending = page.locator('[data-purchase-request-id="purchase-pending"]')
  page.once('dialog', (dialog) => dialog.accept())
  await pending.getByRole('button', { name: '收货入库' }).click()
  await expect(page.getByText('已收货入库', { exact: true })).toHaveCount(1)
  await expect(page.locator('[data-purchase-request-id="purchase-pending"]')).toHaveCount(0)
  await page.getByRole('button', { name: /已处理/ }).click()
  await expect(page.locator('[data-purchase-request-id="purchase-pending"]')).toContainText('已处理')
  expect(await page.evaluate(() => window.__purchaseTest.receiveAttempts)).toBe(1)
})

test('新增供应商复用 Overlay contract 并恢复背景滚动', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/purchase-harness.html')
  await page.getByRole('button', { name: /新增/ }).click()
  const dialog = page.getByRole('dialog', { name: '新增供应商' })
  await expect(dialog).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.body.style.position)).toBe('fixed')
  await expect(dialog.locator('.budu-overlay-scroll')).toHaveCSS('overscroll-behavior-y', 'contain')
  await dialog.getByPlaceholder('供应商名称').focus()
  await expect(dialog.getByRole('button', { name: '保存' })).toBeVisible()
  await dialog.getByRole('button', { name: '取消' }).click()
  await expect.poll(() => page.evaluate(() => document.body.style.position)).toBe('')
})

for (const width of [320, 340, 375, 390, 430]) {
  test(`${width}px 采购表单与移动卡片无横向溢出`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tests/purchase-harness.html')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    const pending = page.locator('[data-purchase-request-id="purchase-pending"]')
    await expect(pending.getByRole('button', { name: '收货入库' })).toBeVisible()
    await expect(pending).toContainText('北京测试供应商')
    const box = await pending.boundingBox()
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: '选择产品' }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
  })
}

test('日期筛选、导出与已处理列表保持可用', async ({ page }) => {
  await page.goto('/tests/purchase-harness.html')
  await page.getByLabel('提交开始日期').fill('2026-08-30')
  await expect(page.locator('[data-purchase-request-id="purchase-pending"]')).toBeVisible()
  await page.getByRole('button', { name: /已处理/ }).click()
  await expect(page.locator('[data-purchase-request-id="purchase-done"]')).toHaveCount(0)
  await page.getByRole('button', { name: '清空日期' }).click()
  await expect(page.locator('[data-purchase-request-id="purchase-done"]')).toBeVisible()
  await page.locator('[data-purchase-request-id="purchase-done"]').getByRole('button', { name: '导出表格' }).click()
  await expect(page.getByText('budu · 货品清单')).toBeVisible()
  await expect(page.locator('.fixed.inset-0.z-\\[90\\]').getByRole('button', { name: '导出表格' })).toBeVisible()
})
