import { expect, test } from '@playwright/test'

test('记录中心只展示任务结构，创建表单进入独立页面', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html?records=1')
  await expect(page.getByRole('heading', { name: '门店调拨 2.0' })).toBeVisible()
  await expect(page.getByRole('tab', { name: /待备货/ })).toBeVisible()
  await expect(page.getByRole('tab', { name: /已发货/ })).toBeVisible()
  await expect(page.getByLabel('调出门店')).toHaveCount(0)
  await page.getByRole('button', { name: '创建调拨' }).click()
  await expect(page.getByRole('button', { name: /核对并提交/ })).toBeDisabled()
  await expect(page.getByRole('heading', { name: '创建调拨' })).toBeVisible()
  await expect(page.getByLabel('调出门店')).toBeVisible()
  await expect(page.getByLabel('调入门店')).toHaveValue('guanshe')
  await expect(page.getByLabel('调入门店')).toBeDisabled()
})

test('产品与物料草稿切换不继承选择、数量或临时状态', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await page.getByRole('button', { name: 'NO.1 树莓', exact: true }).click()
  await page.getByLabel('产品批量数量').fill('6')
  await page.getByRole('tab', { name: '物料' }).click()
  await expect(page.getByRole('textbox', { name: '冰袋数量', exact: true })).toHaveValue('')
  await page.getByRole('textbox', { name: '冰袋数量', exact: true }).fill('3')
  await page.getByRole('tab', { name: '产品' }).click()
  await expect(page.getByRole('button', { name: 'NO.1 树莓', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('产品批量数量')).toHaveValue('6')
  await page.getByRole('tab', { name: '物料' }).click()
  await expect(page.getByRole('textbox', { name: '冰袋数量', exact: true })).toHaveValue('3')
})

test('同店调拨显示精确错误，合法数据经过独立确认层提交', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await page.getByLabel('调出门店').selectOption('guanshe')
  await expect(page.getByRole('alert')).toHaveText('调出门店不能与调入门店相同')
  await page.getByLabel('调出门店').selectOption('tongying')
  await page.getByRole('button', { name: 'NO.1 树莓', exact: true }).click()
  await page.getByLabel('产品批量数量').fill('2')
  await page.getByRole('button', { name: /加入清单/ }).click()
  await page.getByRole('button', { name: /核对并提交/ }).click()
  const dialog = page.getByRole('dialog', { name: '确认调拨信息' })
  await expect(dialog).toContainText('北京通盈中心店 → 北京官舍店')
  expect(await page.evaluate(() => window.__transferTest.requests.length)).toBe(0)
  await dialog.getByRole('button', { name: '确认提交' }).click()
  await expect(page.getByRole('status')).toContainText('等待调出门店备货')
  expect(await page.evaluate(() => window.__transferTest.requests[0])).toMatchObject({ fromStoreKey: 'tongying', toStoreKey: 'guanshe', items: [{ name: 'NO.1树莓', quantity: 2, category: 'product' }] })
})

test('整箱、散颗与混合数量独立录入并保留约重', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await page.getByRole('button', { name: 'NO.2 柠檬', exact: true }).click()
  await expect(page.getByLabel('产品批量数量')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /加入清单/ })).toBeVisible()
  await page.getByRole('textbox', { name: 'NO.2柠檬整箱数量', exact: true }).fill('1')
  await page.getByRole('textbox', { name: 'NO.2柠檬散颗数量', exact: true }).fill('166')
  await expect(page.getByTestId('transfer-product-draft')).toContainText('1箱 + 166颗 · 约3.50kg')
  await page.getByRole('button', { name: /加入清单/ }).click()
  await expect(page.getByText('1箱 + 166颗', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: /核对并提交/ }).click()
  const dialog = page.getByRole('dialog', { name: '确认调拨信息' })
  await expect(dialog).toContainText('1箱 + 166颗')
  await expect(dialog).toContainText('约3.50kg')
  await dialog.getByRole('button', { name: '确认提交' }).click()
  expect(await page.evaluate(() => window.__transferTest.requests.at(-1).items[0])).toMatchObject({ itemId: 'master-p2', boxQuantity: 1, pieceQuantity: 166 })
})

test('0箱0颗不可加入清单', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await page.getByRole('button', { name: 'NO.2 柠檬', exact: true }).click()
  await page.getByRole('button', { name: /加入清单/ }).click()
  await expect(page.getByRole('alert')).toHaveText('请为所有已选产品填写有效数量')
  await expect(page.getByRole('button', { name: /核对并提交/ })).toBeDisabled()
})

test('核对并发货默认等于申请，减量后保留申请与实发事实', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html?records=1')
  await page.locator('[data-transfer-record-id="tr-pending"]').click()
  await expect(page.getByRole('dialog', { name: '调拨详情' })).toContainText('1箱 + 166颗')
  await page.getByRole('button', { name: '核对并发货', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '核对并发货' })
  await expect(dialog).toContainText('实发只能等于或少于申请')
  await expect(dialog.getByRole('textbox', { name: 'NO.2柠檬实发箱数' })).toHaveValue('1')
  await expect(dialog.getByRole('textbox', { name: 'NO.2柠檬实发颗数' })).toHaveValue('166')
  await expect(dialog.getByRole('textbox', { name: '冰袋实发数量' })).toHaveValue('100')
  await dialog.getByRole('textbox', { name: 'NO.2柠檬实发颗数' }).fill('100')
  await dialog.getByRole('textbox', { name: '冰袋实发数量' }).fill('80')
  expect(await page.evaluate(() => window.__transferTest.records.find((item) => item.id === 'tr-pending').status)).toBe('pending')
  await dialog.getByRole('button', { name: '确认实发' }).click()
  await expect(page.getByRole('tab', { name: /已发货/ })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('[data-transfer-record-id="tr-pending"]')).toContainText('发货人 manager-test')
  expect(await page.evaluate(() => window.__transferTest.shipments[0])).toEqual({ items: [{ itemId: 'it-1', shippedBoxQuantity: 1, shippedPieceQuantity: 100 }, { itemId: 'master-m1', shippedQuantity: 80 }] })
  await page.locator('[data-transfer-record-id="tr-pending"]').click()
  const shippedDetail = page.getByRole('dialog', { name: '调拨详情' })
  await expect(shippedDetail).toContainText('申请：1箱 + 166颗')
  await expect(shippedDetail).toContainText('实发：1箱 + 100颗')
  await expect(shippedDetail).toContainText('申请：100件')
  await expect(shippedDetail).toContainText('实发：80件')
  await shippedDetail.getByRole('button', { name: '调拨单图片' }).click()
  await expect.poll(() => page.evaluate(() => window.__transferTest.imageExports)).toBeGreaterThan(0)
  await expect(page.locator('[data-transfer-record-id="tr-legacy"]')).toContainText('已发货')
})

test('核对并发货在客户端拒绝超量与全零', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html?records=1')
  await page.locator('[data-transfer-record-id="tr-pending"]').click()
  await page.getByRole('button', { name: '核对并发货', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '核对并发货' })
  await dialog.getByRole('textbox', { name: 'NO.2柠檬实发颗数' }).fill('167')
  await dialog.getByRole('button', { name: '确认实发' }).click()
  await expect(dialog.getByRole('alert')).toContainText('不能超过申请')
  await dialog.getByRole('textbox', { name: 'NO.2柠檬实发箱数' }).fill('0')
  await dialog.getByRole('textbox', { name: 'NO.2柠檬实发颗数' }).fill('0')
  await dialog.getByRole('textbox', { name: '冰袋实发数量' }).fill('0')
  await dialog.getByRole('button', { name: '确认实发' }).click()
  await expect(dialog.getByRole('alert')).toHaveText('没有实际发货商品')
  expect(await page.evaluate(() => window.__transferTest.shipments.length)).toBe(0)
})

test('调拨详情生成正式 Canvas 图片，历史缺失编码显示横线而不补造', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html?records=1')
  await page.getByRole('tab', { name: /已发货/ }).click()
  await page.locator('[data-transfer-record-id="tr-legacy"]').click()
  const detail = page.getByRole('dialog', { name: '调拨详情' })
  await expect(detail).toContainText('编码 —')
  await expect(detail).toContainText('历史发货记录')
  await detail.getByRole('button', { name: '调拨单图片' }).click()
  await expect.poll(() => page.evaluate(() => window.__transferTest.imageExports)).toBeGreaterThan(0)
})

for (const width of [320, 340, 375, 390, 430]) {
  test(`${width}px 创建与记录页面无横向溢出`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tests/transfer-harness.html?records=1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    await page.locator('[data-transfer-record-id="tr-pending"]').click()
    const detail = page.getByRole('dialog', { name: '调拨详情' })
    await detail.getByRole('button', { name: '核对并发货' }).click()
    const shipment = page.getByRole('dialog', { name: '核对并发货' })
    await expect(shipment.getByRole('button', { name: '确认实发' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    const shipmentBox = await shipment.boundingBox()
    expect(shipmentBox.x).toBeGreaterThanOrEqual(0)
    expect(shipmentBox.x + shipmentBox.width).toBeLessThanOrEqual(width)
    await shipment.getByRole('button', { name: '关闭' }).click()
    await detail.getByRole('button', { name: '关闭' }).click()
    await page.getByRole('button', { name: '创建调拨' }).click()
    const productButton = page.getByRole('button', { name: 'NO.1 树莓', exact: true })
    await expect(productButton.getByTestId('transfer-product-name')).toHaveText('树莓')
    await expect(productButton).not.toContainText('NO.1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    const submitBar = await page.getByTestId('transfer-submit-bar').boundingBox()
    const bottomNav = await page.getByTestId('mobile-bottom-nav').boundingBox()
    expect(submitBar.y + submitBar.height).toBeLessThanOrEqual(bottomNav.y + 1)
    await page.evaluate(() => window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' }))
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
    const lastSection = await page.locator('[data-testid="transfer-create-page"] > section').last().boundingBox()
    const submitAfterScroll = await page.getByTestId('transfer-submit-bar').boundingBox()
    expect(lastSection.y + lastSection.height).toBeLessThanOrEqual(submitAfterScroll.y)
    await expect(page.getByTestId('transfer-submit-bar')).toHaveAttribute('style', /safe-area-inset-bottom/)
  })
}

test('1440px 桌面核对并发货 Sheet 无横向溢出', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/tests/transfer-harness.html?records=1')
  await page.locator('[data-transfer-record-id="tr-pending"]').click()
  await page.getByRole('button', { name: '核对并发货' }).click()
  const shipment = page.getByRole('dialog', { name: '核对并发货' })
  await expect(shipment).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
  const box = await shipment.boundingBox()
  expect(box.width).toBeLessThanOrEqual(576)
})

test('调拨选择器只读取启用的 PostgreSQL 主数据', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await expect(page.getByRole('button', { name: 'NO.1 树莓', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '物料' }).click()
  await expect(page.getByRole('textbox', { name: '冰袋数量', exact: true })).toBeVisible()
  await expect(page.getByText('停用纸袋', { exact: true })).toHaveCount(0)
})

test('调拨产品复用分类主数据并支持分类、名称、编号与 SKU 搜索', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html')
  await page.getByRole('button', { name: '创建调拨' }).click()
  await page.getByRole('button', { name: '糖果' }).click()
  await expect(page.getByRole('button', { name: 'NO.1 树莓', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'NO.2 柠檬', exact: true })).toHaveCount(0)
  await expect(page.getByText('停用产品', { exact: true })).toHaveCount(0)
  await page.getByLabel('搜索调拨产品').fill('树莓')
  await expect(page.getByRole('button', { name: 'NO.1 树莓', exact: true })).toBeVisible()
  await page.getByLabel('搜索调拨产品').fill('NO.2')
  await expect(page.getByRole('button', { name: 'NO.2 柠檬', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '未分类' }).click()
  await expect(page.getByRole('button', { name: 'NO.2 柠檬', exact: true })).toBeVisible()
  await page.getByTestId('transfer-product-draft').getByRole('button', { name: '全部', exact: true }).click()
  await page.getByLabel('搜索调拨产品').fill('BUDU-CHOC-WA-03')
  const skuMatch = page.getByRole('button', { name: 'GIFT-1 礼盒产品', exact: true })
  await expect(skuMatch).toBeVisible()
  await expect(skuMatch).not.toContainText('BUDU-CHOC-WA-03')
})

test('Excel 导出提供日期、门店多选及产品物料筛选', async ({ page }) => {
  await page.goto('/tests/transfer-harness.html?records=1')
  await page.getByRole('button', { name: '导出 Excel' }).click()
  const dialog = page.getByRole('dialog', { name: '导出门店物资调拨' })
  await expect(dialog).toContainText('只统计已发货，以发货确认时间为准')
  await dialog.getByLabel('导出开始日期').fill('2026-08-01')
  await dialog.getByLabel('导出结束日期').fill('2026-08-31')
  await expect(dialog.getByLabel(/导出门店/)).toHaveCount(4)
  await dialog.getByLabel('导出门店北京通盈中心店').uncheck()
  await dialog.getByRole('button', { name: '产品', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '导出汇总 Excel' })).toBeVisible()
})
