import { Check, X } from 'lucide-react'

const inputClass = 'mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none focus:border-budu-400 disabled:bg-slate-50'

export default function MaterialEditor({ value, busy, error, onChange, onClose, onSave }) {
  const update = (key, next) => onChange({ ...value, [key]: next })
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-900/45 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label={value.id ? '编辑物料' : '新增物料'}>
    <form onSubmit={(event) => { event.preventDefault(); onSave() }} className="flex max-h-[92dvh] w-full max-w-lg flex-col overflow-hidden rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl">
      <div className="flex shrink-0 items-center border-b border-slate-100 px-5 py-4"><div><h3 className="font-black text-slate-900">{value.id ? '编辑物料' : '新增物料'}</h3><p className="mt-0.5 text-xs text-slate-400">保留历史记录 · 不用于 POS 销售</p></div><button type="button" onClick={onClose} className="ml-auto grid h-10 w-10 place-items-center rounded-xl text-slate-400" aria-label="关闭"><X className="h-5 w-5" /></button></div>
      <div className="min-h-0 space-y-4 overflow-y-auto p-5">
        {error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-600">{error}</p>}
        <label className="block text-xs font-bold text-slate-500">物料名称<input required maxLength={50} value={value.name} onChange={(event) => update('name', event.target.value)} className={inputClass} /></label>
        <div className="grid gap-3"><label className="block text-xs font-bold text-slate-500">SKU<input readOnly value={value.sku || ''} placeholder="保存时自动生成" className={inputClass} /></label><label className="block text-xs font-bold text-slate-500">产品编号<input readOnly value={value.code || ''} placeholder="保存时自动生成" className={inputClass} /></label></div>
        <div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold text-slate-500">物料零售价（元）<input required inputMode="decimal" value={value.salePrice} onChange={(event) => update('salePrice', event.target.value)} className={inputClass} /></label><label className="block text-xs font-bold text-slate-500">物料成本价（元）<input required inputMode="decimal" disabled={Boolean(value.id)} value={value.id && !value.costVisible ? '' : value.costPrice} placeholder={value.id && !value.costVisible ? '无成本查看权限' : ''} onChange={(event) => update('costPrice', event.target.value)} className={inputClass} />{value.id && value.costVisible && <span className="mt-1 block text-[10px] text-slate-400">成本调整请使用列表中的成本历史</span>}</label></div>
        <label className="block text-xs font-bold text-slate-500">排序<input required type="number" min="0" max="999999" value={value.sortOrder} onChange={(event) => update('sortOrder', event.target.value)} className={inputClass} /></label>
        <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm font-bold text-slate-600">门店调拨启用<input type="checkbox" checked={value.enabled} onChange={(event) => update('enabled', event.target.checked)} className="h-5 w-5 accent-budu-500" /></label>
        <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm font-bold text-slate-600">合作商可补货<input type="checkbox" checked={value.partnerReplenishmentEnabled} onChange={(event) => update('partnerReplenishmentEnabled', event.target.checked)} className="h-5 w-5 accent-budu-500" /></label>
        {value.partnerReplenishmentEnabled && <div className="space-y-3 rounded-2xl bg-amber-50 p-4"><label className="block text-xs font-bold text-slate-600">物料补货方式<select aria-label="物料补货方式" required value={value.partnerOrderUnit || ''} onChange={(event) => update('partnerOrderUnit', event.target.value)} className={inputClass}><option value="">请选择</option><option value="NATIVE">现有单位</option><option value="PCS">单件 PCS</option><option value="KG">重量 KG</option></select></label>{value.partnerOrderUnit === 'NATIVE' && <label className="block text-xs font-bold text-slate-600">物料单位<input required maxLength={20} value={value.unit || ''} onChange={(event) => update('unit', event.target.value)} placeholder="盒 / 个 / 包" className={inputClass} /></label>}<label className="block text-xs font-bold text-slate-600">独立补货标准报价（元/{value.partnerOrderUnit === 'KG' ? 'kg' : value.partnerOrderUnit === 'PCS' ? '件' : value.unit || '单位'}）<input required inputMode="decimal" value={value.partnerMaterialPrice || ''} onChange={(event) => update('partnerMaterialPrice', event.target.value)} className={inputClass} /></label><p className="text-xs text-amber-700">单独填写补货报价，再按合作商折扣计价；不会使用零售价或成本价代填。</p></div>}
      </div>
      <div className="flex shrink-0 justify-end gap-3 border-t border-slate-100 px-5 py-4 pb-[max(1rem,env(safe-area-inset-bottom))]"><button type="button" onClick={onClose} className="btn-secondary min-h-11 px-5">取消</button><button disabled={busy} className="btn-primary min-h-11 px-6"><Check className="h-4 w-4" />{busy ? '保存中…' : '保存物料'}</button></div>
    </form>
  </div>
}
