export const OPERATIONAL_IDENTITY_TYPES = Object.freeze({
  STANDARD: 'STANDARD',
  NON_EMPLOYEE_OPERATIONAL_SUBSTITUTE: 'NON_EMPLOYEE_OPERATIONAL_SUBSTITUTE',
})

export const PAYROLL_PARTICIPANT_TYPES = Object.freeze({
  EMPLOYEE: 'EMPLOYEE',
  NON_EMPLOYEE_SUBSTITUTE: 'NON_EMPLOYEE_SUBSTITUTE',
  LEGACY_EMPLOYEE_COMPATIBLE: 'LEGACY_EMPLOYEE_COMPATIBLE',
  LEGACY_UNKNOWN: 'LEGACY_UNKNOWN',
})
